### ISSUE TITLE
switching languages dynamically

### ISSUE THREAD

**Issue by scriptworld-git** [kitian616/jekyll-TeXt-theme#47]
since you implemented to choose different languages in the config yaml, why not put this decision to the user viewing the page ? make a simple dropdown box in the bottom or at the top to choose between different languages.
I don't know if this is possible but the interface for different languages is already there so it should be only a little tweak :)

**Comment by kitian616** [comment]
IMO, a site that can chose languages always mean that this is a muti-languages site. If I choose a different language, all the texts in the page must also turn to the choosen language.
The purpose of language config is to tell the reader and search engine the page's language. since the poster may use different languages.
But I am thinking about muti-languages post, the same post with different languages.

**Comment by mqo00** [comment]
Hi, so is this dynamic language switching function implemented? If not and if I want to add it, what's the most convenient way that works with your theme? Thanks.
